### ISSUE TITLE
Beams colored based on damage

### ISSUE THREAD

**Issue by SylveonBottle** [tf2cheater2013/Fedoraware#138]
Change the color of beams based on how much damage the shot did.

Potential (but probably bad) method of how you could do this:
When firing, don't spawn beams for 16ms.
Check the last damage you did, possibly based on this:
https://github.com/tf2cheater2013/Fedoraware/blob/d818752b5dae18101a61ab66e909289f7cbd190e/Fedoraware/TeamFortress2/TeamFortress2/Features/ChatInfo/ChatInfo.cpp#L80

Set color based on the last damage dealt
Have a color value for 0dmg, 1dmg, and 300dmg. 
This lets users set 0dmg beams (when shooting randomly at no target) to whatever they want. For example, fully transparent beams so you don't see beams unless they deal damage.
Color value for 1dmg to 300dmg could be for example green to red, so the beam is more red the more damage it does. Or transparent to blue, so the beam becomes more visible the more damage it dealt. 
With that, it may be possible to adjust the size of the beam based on damage as well, or even the model of the beam if it's above 300dmg.

We could also do something like crit beams.

Possible examples of what this could produce:
-Crit beams could be rainbow colored, so they're super noticable
-The more damage a beam does, the faster Beam Speed is
-Change Beam Brightness based on damage dealt (less damage = less visible shots)
-Change crit beams to use Short Circuit instead

Would this be possible?

**Comment by johnathon-walnut** [comment]
Beams are fired from the FireBullets hook, which afaik isn't related to the event for damage (as they show even when you dont damage people). I don't really like the idea of not firing for 16ms as I imagine delaying like that would add a noticeable lag at least in the way i'm thinking about it. Crit beams should be possible as the weapon fired from gets passed as an argument, so you can check pWeapon->IsCritBoosted(). Beam speed doesn't really affect how fast the beam goes, it seems to affect flags like FBEAM_FADEOUT and FBEAM_SHADEOUT. I don't know if there's a way to make it act like a tracer but if you know, do tell me. I also don't think that the particle tracers are sprites, which is what the beam needs to draw. Furthermore, you can't just set the beam sprite texture to any sprite, for some reason only certain ones work, if you put in a wrong one it seems to put the beam in a random place and it disappears really quickly. Furthermore, I think changes like these would be best added to a personally maintained builds as, while it's cool, it's not really that big of a thing. I appreciate the suggestions and idea on implementation, but this isn't something that I would personally do myself, if you want to try adding it feel free. One way i'm thinking it could be done is to queue beams up, then add like a bool set to true at the end of firegameevent stuff and then do the beams there with a queue made in firebullets?

FireGameEvent -> player_hurt -> draw beams = false -> edit/create queue of beams to be cool and modify to be crit/whatever effects u want -> draw beams = true

FireBullets -> always queue beams up -> dont call original, dont draw beams here 

CreateMove -> clear queue and draw beams at the end of every call

Dunno if this is sound logic but that's how i would go about implementing such a thing, seems a bit overengineered and pointless for what you get in return though.

Only reason I'm thinking of doing it like this is because I don't know what order each thing gets called in, is it firebullets then event or the other way round? if its event then firebullets then sure it could be easy but I don't know that and frankly can't be bothered to test.

**Comment by lbydesync** [comment]
DON'T USE PASTES LOL!
on this note why even use beam, find a mod to replace Machina

**Comment by johnathon-walnut** [comment]
What? Why would you "replace machina"? You can use literally any particle tracer you want. Furthermore, beams are different to particle tracers and are nothing like the machina.

**Comment by johnathon-walnut** [comment]
Maybe estimated damage? Could be interesting

**Comment by johnathon-walnut** [comment]
Like multiply base damage by distance, remap that from 0 to 360 and use it as the hue?

**Comment by xxmyn** [comment]
why reopen manz...
