### ISSUE TITLE
logs magically get enabled (top left corner) without being enabled

### ISSUE THREAD

**Issue by ShiroSeby** [tf2cheater2013/Fedoraware#92]
it's somehow enabled without even being turned on
and also sometimes it doesn't work and when i try to enable the log (for example damage log) it doesn't show

1 more thing, the gui notif time is by default 5.0 when the max you can manually set is 3.0

**Comment by gayblackirony** [comment]
ok

**Comment by xxmyn** [comment]
Actually by ctrl + clicking the field you can set the value to whatever you want.

The lighter colour in comboboxes means it is enabled, the darker colour means it is disabled, I have not been able to recreate the issue you described with my config, assuming the issue was config / user based (and since u have uploaded neither ur config or ur genetic sequence I can't do any testing)
